//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Rwer.
    /// </summary>
    //  *** Start programmer edit section *** (rwer CustomAttributes)

    //  *** End programmer edit section *** (rwer CustomAttributes)
    [AutoAltered()]
    [Caption("Rwer")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("rwerE", new string[0])]
    [View("rwerL", new string[0])]
    public class rwer : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (rwer CustomMembers)

        //  *** End programmer edit section *** (rwer CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "rwerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View rwerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("rwerE", typeof(IIS.mu7.rwer));
                }
            }
            
            /// <summary>
            /// "rwerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View rwerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("rwerL", typeof(IIS.mu7.rwer));
                }
            }
        }
    }
}
